use Oishi;
GO

-- Admin
DROP LOGIN OishiAdmin;
DROP USER OishiAdminU;
DROP ROLE OishiAdminR;

CREATE LOGIN OishiAdmin WITH PASSWORD = 'admin';
CREATE USER OishiAdminU FOR LOGIN OishiAdmin;

CREATE ROLE OishiAdminR;
GO
GRANT ALTER, REFERENCES, CONTROL, VIEW DEFINITION ON SYMMETRIC KEY::MySymKey TO OishiAdminR WITH GRANT OPTION;
GRANT ALTER, REFERENCES, CONTROL, VIEW DEFINITION ON CERTIFICATE::MyCert TO OishiAdminR WITH GRANT OPTION;

GRANT UNMASK to OishiAdminR;
GRANT EXECUTE ON Encrypt TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON EncryptByLogin TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON Decrypt TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON GetAllUsers TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllOrders TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllUnconfirmedOrders TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllDishTypes TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllDishes TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetDishesByCategory TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllRestables TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllReviews TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON DeleteUser TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteDish TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteDishType TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteTable TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteReview TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteOrder TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON DeleteAllUsers TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON AddAdmin TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON ConfirmOrder TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON ExportUsersToXML TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON ImportUsersFromXML TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON InsertIntoDishtypes TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertIntoMenu TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertIntoRestables TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON InsertUsers TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertDishtypes TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertMenu TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertRestables TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertOrders TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON InsertReviews TO OishiAdminR WITH GRANT OPTION;

GRANT EXECUTE ON UpdateUser TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON UpdateDishType TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON UpdateDish TO OishiAdminR WITH GRANT OPTION;
GRANT EXECUTE ON UpdateTable TO OishiAdminR WITH GRANT OPTION;
GO
exec sp_addrolemember 'OishiAdminR', 'OishiAdminU';
GO

-- Client
DROP LOGIN OishiClient;
DROP USER OishiClientU;
DROP ROLE OishiClientR;

CREATE LOGIN OishiClient WITH PASSWORD = '1234';
CREATE USER OishiClientU FOR LOGIN OishiClient;

CREATE ROLE OishiClientR;
GO
GRANT EXECUTE ON Registrate TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON Authorize TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON AddReview TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON MakeOrder TO OishiClientR WITH GRANT OPTION;

GRANT EXECUTE ON GetAllDishes TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON GetDishesByCategory TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllRestables TO OishiClientR WITH GRANT OPTION;
GRANT EXECUTE ON GetAllReviews TO OishiClientR WITH GRANT OPTION;
GRANT ALTER, REFERENCES, CONTROL, VIEW DEFINITION ON SYMMETRIC KEY::MySymKey TO OishiClientR WITH GRANT OPTION;
GRANT ALTER, REFERENCES, CONTROL, VIEW DEFINITION ON CERTIFICATE::MyCert TO OishiClientR WITH GRANT OPTION;
GO
exec sp_addrolemember 'OishiClientR', 'OishiClientU';
GO



